### PR TITLE
#160885053 Set up

### PR DESCRIPTION
**Pull request by gwako94**
#### What does this PR do?
Initialize work environment

#### Description of Task to be completed?
Have environment set up

#### What are the relevant pivotal tracker stories?
#160884705

### CODE REVIEW

**Comment by Darius-Ndubi** [comment]
Hey nice structure man, its easier to work with.

**Comment by verenceLola** [comment]
Looks good to merge. You may proceed.

**Comment by fabischolasi** [comment]
merge

**Comment by jamesbeamie** [comment]
ok

**Pull request merged**
